apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-manual-run-cql-4-x
  namespace: ops-spaas
  labels:
    app: ycsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: topology.kubernetes.io/zone
      #          operator: In
      #          values:
      #          - ap-northeast-1d
      containers:
      - name: ycsb
        #image: public.ecr.aws/j9i4p5a8/ycsb:cql_4_x_v1
        image: public.ecr.aws/j9i4p5a8/ycsb:ddb_alternator_v1
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1G
            cpu: 1
          limits:
            memory: 1G
            cpu: 1
