apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-manual-run
  namespace: realtime-streaming
  labels:
    app: ycsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
      - name: ycsb
        image: public.ecr.aws/j9i4p5a8/ycsb:v3
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        resources:
          requests:
            memory: 20G
            cpu: 8
          limits:
            memory: 20G
            cpu: 8
